//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContracts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditoria
    {
        public int ID { get; set; }
        public string tabla { get; set; }
        public string accion { get; set; }
        public string modificadoPor { get; set; }
        public System.DateTime fecha { get; set; }
    }
}
