//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContracts
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Clases
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clases()
        {
            this.referenciaHorarios_referenciaClases = new HashSet<referenciaHorarios_referenciaClases>();
        }
    
        public int ID { get; set; }
        public string nombre { get; set; }
        public string dia { get; set; }
        [DisplayName("hora inicio")]
        public System.DateTime horaInicio { get; set; }
        [DisplayName("hora fin")]
        public System.DateTime horaFin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<referenciaHorarios_referenciaClases> referenciaHorarios_referenciaClases { get; set; }
    }
}
