//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContracts
{
    using System;
    using System.Collections.Generic;
    
    public partial class referenciaHorarios_referenciaClases
    {
        public int ID { get; set; }
        public int IDHorario { get; set; }
        public int IDClase { get; set; }
    
        public virtual Clases Clases { get; set; }
        public virtual Horarios Horarios { get; set; }
    }
}
