//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContracts
{
    using System;
    using System.Collections.Generic;
    
    public partial class referenciaRutinas_referenciaEjercicios
    {
        public int ID { get; set; }
        public int IDRutina { get; set; }
        public int IDEjercicio { get; set; }
    
        public virtual Ejercicios Ejercicios { get; set; }
        public virtual Rutinas Rutinas { get; set; }
    }
}
