//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContracts
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.ComentariosEventos = new HashSet<ComentariosEventos>();
            this.ComentariosNoticias = new HashSet<ComentariosNoticias>();
            this.HistorialMedico = new HashSet<HistorialMedico>();
            this.Horarios = new HashSet<Horarios>();
            this.Medidas = new HashSet<Medidas>();
            this.Medidas1 = new HashSet<Medidas>();
            this.Mensaje = new HashSet<Mensaje>();
            this.Mensaje1 = new HashSet<Mensaje>();
            this.PagosRealizados = new HashSet<PagosRealizados>();
            this.referenciaUsuarios_referenciaEventos = new HashSet<referenciaUsuarios_referenciaEventos>();
            this.referenciaUsuarios_referenciaNotificaciones = new HashSet<referenciaUsuarios_referenciaNotificaciones>();
            this.referenciaUsuarios_referenciaOfertas = new HashSet<referenciaUsuarios_referenciaOfertas>();
        }
    
        public int ID { get; set; }
        public int cedula { get; set; }
        public string nombre { get; set; }
        [DisplayName("Primer apellido")]
        public string apellido1 { get; set; }
        [DisplayName("segundo apellido")]
        public string apellido2 { get; set; }
        public string correo { get; set; }
        public string contrasena { get; set; }
        public string tipo { get; set; }
        public string sexo { get; set; }
        [DisplayName("telefono")]
        public int telefono1 { get; set; }
        [DisplayName("otro telefono")]
        public int telefono2 { get; set; }
        public string ocupacion { get; set; }
        [DisplayName("Estado civil")]
        public string estadoCivil { get; set; }
        [DisplayName("Habilitado")]
        public bool habilitado { get; set; }
        [DisplayName("fecha de ingreso")]
        public System.DateTime fechaIngreso { get; set; }
        [DisplayName("fecha de pago")]
        public System.DateTime fechaPago { get; set; }
        public int IDRutina { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComentariosEventos> ComentariosEventos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComentariosNoticias> ComentariosNoticias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialMedico> HistorialMedico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horarios> Horarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medidas> Medidas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medidas> Medidas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mensaje> Mensaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mensaje> Mensaje1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagosRealizados> PagosRealizados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<referenciaUsuarios_referenciaEventos> referenciaUsuarios_referenciaEventos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<referenciaUsuarios_referenciaNotificaciones> referenciaUsuarios_referenciaNotificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<referenciaUsuarios_referenciaOfertas> referenciaUsuarios_referenciaOfertas { get; set; }
        public virtual Rutinas Rutinas { get; set; }
    }
}
