//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContracts
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaTablaHistorialPlieguesHombres
    {
        public int ID { get; set; }
        public string nombre { get; set; }
        public int Id_Historial_medico { get; set; }
        public int ID_Medidas_del_usuario { get; set; }
        public int Id_Pliegues_hombres { get; set; }
    }
}
